### PR TITLE
added notebook with erddappy and simple class wrap

### PR DESCRIPTION
**Pull request by callumrollo**

### CODE REVIEW

**Comment by callumrollo** [comment]
This PR address issue #1

**Comment by ocefpaf** [comment]
Please ignore the CI errors for now. We don't really have anything to test yet.

**Comment by ocefpaf** [comment]
nbviewer link to facilitate the vizualitation of the notebook: https://nbviewer.jupyter.org/github/callumrollo/ohw20-proj-glide-data-fetcher/blob/master/notebooks/demo.ipynb

How do you envision the time/space query API? `argopy` has a `.region` but region does not really encompass time IMO. What would be a better name that would mean both? Maybe just `.query`?

**Comment by callumrollo** [comment]
`.query` sounds sensible. I envisage taking the arguments supplied to this and passing them to errdappy's `constraints`

 working on it now

**Comment by callumrollo** [comment]
This commit addes a `query` method as discussed above. It's rough araound the edges and requires the user to supply lat, lon and time constraints all at once and in the correct order

**Comment by LindsayRAbrams** [comment]
Just now catching up! I agree, `.query` would be better. And we will do a something similar to `argopy` `.float` as well right? What if we name that one `.id_query`? Are those too similar?

**Comment by ocefpaf** [comment]
@LindsayRAbrams when you have some time can you read the notebook and let us know what you think? A good API is usually ok when someone can read and understand what is going on without asking the devs about it, so you'll be our "proof reader." If you don't understand it, that means we need to work a bit more on the design.

**Comment by ocefpaf** [comment]
> Just now catching up! I agree, `.query` would be better. And we will do a something similar to `argopy` `.float` as well right? What if we name that one `.id_query`? Are those too similar?

Yep. But I was thinking about using the ERDDAP `dataset_id` instead, so we can get ERDDAP info tables and map 1-1 there.

**Comment by callumrollo** [comment]
This is my first time working with classes and it's a very rough notebook. Let me know if stuff doesn't make sense and feel free to add comments/overwrite

**Comment by ocefpaf** [comment]
> This is my first time working with classes and it's a very rough notebook. Let me know if stuff doesn't make sense and feel free to add comments/overwrite

Don't worry about that part now. When we port this to the library I'll guide you there. (Although I'm not an expert as well :smile:).

My main goal is to come up with an API that will be easy to use and that users will find pleasant to work with. The "raw" erddadpy are a bit involved and not really meant to be easy for a specific dataset. When we narrow the scope, like glider or argo, we can do better than erddapy.

**Comment by LindsayRAbrams** [comment]
Yes reviewing the notebook now. You both definitely have more experience than me so I can definitely see if there is anything that doesn't make sense to me

**Comment by LindsayRAbrams** [comment]
I can mostly follow along so far. I have a few questions/comments:
1. So `glider_grab.fetcher.dataset_id = "sp022-20170209T1616"` is basically the equivalent to argopy's `.float` right?
2. Are there any other glider variables we would want to include? Do any of these datasets include dissolved oxygen or chlorophyll concentration? 
3. The only thing I was kinda confused about was the `time_parse` function. Is this necessary because erddapy requires the time to be in ISO 8601 format?
4. I really like the 'glider_grab.query' function, very easy to use like argopy's `.region`

**Comment by callumrollo** [comment]
Thanks for the feedback Lindsay!

1. So `glider_grab.fetcher.dataset_id = "sp022-20170209T1616"` is basically the equivalent to argopy's `.float` right?
Sort of, these strings identify a glider but also a time as, unlike floats, gliders are redeployed (except those donated to Neptune). The class I've just added to generate a list of available datasets could be expanded to identify multiple datasets from the same glider perhaps?

2. Are there any other glider variables we would want to include? Do any of these datasets include dissolved oxygen or chlorophyll concentration? 
Yes! We want to expand this list but, at present, if you send a request for a variable that is not present on that server, you get an HTTP error that will halt your script. This needs to be looked into. Maybe a list of variables available on each server?

3. The only thing I was kinda confused about was the `time_parse` function. Is this necessary because erddapy requires the time to be in ISO 8601 format?
You're right that this isn't strictly necessary. With the time parser though, users can imput arbitrary datestrings like "2020-02-03" or "4th May 1970" and the parser will make the proper timestamp to pass to erddappy

4. I really like the 'glider_grab.query' function, very easy to use like argopy's `.region`
That's the plan. Imitation is the highest form of flattery :)

**Comment by ocefpaf** [comment]
> except those donated to Neptune

:rofl:

**Pull request merged**
