### PR TITLE
Wrap to_pandas

### PR DESCRIPTION
**Pull request by ocefpaf**
@LindsayRAbrams and @callumrollo I modified the notebook to call the module and wrapped the `to_pandas` method in the class. There are some other changes when I applied pre-commit that I can comment on our meeting today.

### CODE REVIEW

**Comment by callumrollo** [comment]
These look like good commits to me. Happy for you to approve and merge @LindsayRAbrams I think with the removal of hardoded glider id and server we can declare this a sane API and close issue #1

**Comment by ocefpaf** [comment]
> These look like good commits to me. Happy for you to approve and merge @LindsayRAbrams I think with the removal of hardcoded glider id and server we can declare this a sane API and close issue #1


There is still a problem with the search, we are constraining a glider_id and not searching within those constraint. I'll fix that in another PR.

**Comment by ocefpaf** [comment]
Pre-commit is failing on the codespell b/c it gets confused with the notebook outputs. I'm clearing the notebooks and we can run them using the CI only when we want to, like for building docs. That means we should always commit notebooks without the outputs.

**Comment by ocefpaf** [comment]
Pre-commit should fail now on the docstring coverage. That is fine, we can address it later.
If Travis-CI passes now this is good for another round of review/merge!

**Pull request merged**
